-   id: pyspelling-docker
    name: Pyspelling in docker
    description: Pyspelling with aspell using Dockerfile of github action, based on https://github.com/rojopolis/spellcheck-github-actions
    language: docker_image
    entry: docker.io/jonasbn/github-action-spellcheck:latest
